export const actionTypes = {
  FETCH_USER_LIST: "FETCH_USER_LIST",
  FETCH_USER_DETAIL: "FETCH_USER_DETAIL",
  SEARCH_USER: "SEARCH_USER",
  DANG_NHAP: "DANG_NHAP",
  DANG_XUAT: "DANG_XUAT",
  FETCH_FILM_LIST: "FETCH_FILM_LIST",
  FETCH_FILM_DETAIL: "FETCH_FILM_DETAIL",
};
